proyecto_final/StoreProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('signup/',signup_view, name='signup'),
    path('about/',about, name='about'),
    path('login/',login_view, name='login'),
    path('profile/',profile_view, name='profile'),
    path('profile/edit/',profile_edit, name='profile_edit'),
    path('logout/',LogoutView.as_view(template_name='logout.html'), name='logout')
]

proyecto_final/orders/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('checkout/<int:product_id>/', create_order, name='checkout' ),
    path('success/', order_success, name= 'order_success'),
    path('sumary/', cart_summary, name= 'cart_summary'),
    path('add/', cart_add, name= 'cart_add'),
    path('delete/', cart_delete, name= 'cart_delete'),
]

proyecto_final/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    age = models.IntegerField(default=0)
    address = models.CharField(max_length=255, default='Default Address')

class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(default='avatares/Login_default_Avatar.png',upload_to='avatares', blank=True, null=True)

proyecto_final/accounts/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserChangeForm

class UserEditForm(UserChangeForm):
    password = None
    email = forms.EmailField(label='Ingrese su email:', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Apellido', widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'class': 'form-control'}))
    age = forms.IntegerField(label='Edad', widget=forms.NumberInput(attrs={'class': 'form-control'}))
    address = forms.CharField(label='Domicilio', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Contraseña', required=False, widget=forms.PasswordInput(attrs={'class': 'form-control password-input'}))
    password2 = forms.CharField(label='Repetir Contraseña', required=False, widget=forms.PasswordInput(attrs={'class': 'form-control password-input'}))
    
    class Meta:
        model = UserProfile
        fields = ['email', 'last_name', 'first_name', 'age', 'address']

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise forms.ValidationError('Deben cohincidir las contraseñas')
        return password2

class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ['imagen']
        widgets = {
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

proyecto_final/accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserEditForm, AvatarForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from .models import Avatar


# Create your views here.
def index(req):
    avatar_url = None
    if req.user.is_authenticated:
        try:
            avatar = Avatar.objects.get(user=req.user)
            avatar_url = avatar.imagen.url
        except Avatar.DoesNotExist:
            avatar_url = None

    return render(req, 'index.html', {"url": avatar_url})

@csrf_protect
def login_view(req):
    if req.method == 'POST':
        form = AuthenticationForm(req, data=req.POST)
        if form.is_valid():
            user_name = form.cleaned_data.get('username')
            user_password = form.cleaned_data.get('password')
            
            user = authenticate(username=user_name, password=user_password)

            if user is not None:
                login(req, user)
                req.session['username'] = user_name
                return render(req,'profile.html',{'user': user})
            else:
                return render(req, 'login.html', {'form': form, "message": "Credenciales incorrectas"})
        else:
            return render(req, 'login.html', {'form': form, "message": "Formulario inválido"})    
    else:
        form = AuthenticationForm()
    return render(req,'login.html',{'form':form})

def signup_view(req):
    if req.method == 'POST':
        form = UserCreationForm(req.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()
            return redirect('login')
        else:
            return render(req, 'signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(req, 'signup.html', {'form': form})

@login_required
def profile_view(req):
    user = req.user
    
    try:
        avatar = Avatar.objects.get(user=user)
        avatar_url = avatar.imagen.url
    except Avatar.DoesNotExist:
        avatar_url = None
    context = {
        'username': user.username,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
        'age': getattr(user, 'age', 'No especificado'),  
        'address': getattr(user, 'address', 'No especificado'),
        'avatar_url': avatar_url,
    }
    return render(req, 'profile.html', context)

@login_required
def profile_edit(req):
    user = req.user
    try:
        avatar = Avatar.objects.get(user=user)
    except Avatar.DoesNotExist:
        avatar = Avatar(user=user)

    if req.method == 'POST':
        form = UserEditForm(req.POST, instance= user)
        avatar_form = AvatarForm(req.POST, req.FILES, instance=avatar)
        if form.is_valid() and avatar_form.is_valid():
            data = form.cleaned_data
            user.first_name = data['first_name']
            user.last_name = data['last_name']
            user.email = data['email']
            user.age = data['age']
            user.address = data['address']
            if data['password1']:
                user.set_password(data['password1'])
            
            user.save()
            avatar.save()
            
            return render(req,'profile.html', {'avatar_url': avatar.imagen.url})
        else:
            return render(req, 'profileEditForm.html', {'form': form, 'avatar_form': avatar_form})
    else:
        form = UserEditForm(instance= user)
        avatar_form = AvatarForm(instance=avatar)
        return render(req, 'profileEditForm.html', {'form': form, 'avatar_form': avatar_form})
def about(req):
    return render(req, 'about.html', {})

proyecto_final/accounts/templates/about.html
{% extends 'base.html' %}

{% block containBody %}
<section class="py-5">
    <div class="container">
        <div class="d-flex flex-column text-center">
            <div class="vh-75 mb-4">
                <img class="card-img-top mb-5 mb-md-0" src="../../media/upload/¡Hola! Me llamo Christian..jpg" alt="Imagen de TecnoStore" />
            </div>
            <div>
                <h1 class="display-5 fw-bolder">Acerca de</h1>
                <div class="fs-5 mb-5">
                    <h2>TecnoStore</h2>
                </div>
                <p class="lead">
                    Ecommerce que ofrece productos tecnológicos con precios competitivos a travez de ofertas especiales a productos especificos. Donde el usuario puede registrarse, logearse y editar su perfil(datos personales y avatar) y segun si es administrador puede agregar, eliminar o editar los productos que se ofrece por la plataforma.
                </p>
                <h3>Objetivo</h3>
                <p class="lead">
                    Demostrar lo aprendido en el curso de python orientado al desarrollo web utilizando Django como framework.
                </p>
            </div>
        </div>
    </div>
</section>



{% endblock containBody %}

proyecto_final/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>TecnoStore</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core  FontAwesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- Core theme jQuery-->
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'index' %}">TecnoStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Acerca de</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tienda</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'product_list' %}">Productos</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span>
                        </button>
                    </form>
                    
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="btn btn-secondary">Perfil</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="btn btn-secondary">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        
        {% block containBody %}        
        
        {% endblock containBody %}

        <section class="py-5"></section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Christian Bustamante 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

proyecto_final/accounts/templates/index.html
{% extends 'base.html' %}

{% block containBody %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner ">
        <div class="carousel-item active">
            <img src="https://images.pexels.com/photos/341523/pexels-photo-341523.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="d-block w-100" alt="">
        </div>
        <div class="d-flex justify-content-center align-items-center position-absolute top-50 start-50 translate-middle">
            <div class="text-center text-white">
                <h1 class="display-2 fw-bolder">TecnoStore</h1>
                <p class="lead fw-normal text-white-70 mb-0">Tecnology and style</p>
            </div>
        </div>

    </div>
</div>
{% endblock containBody %}

proyecto_final/accounts/templates/login.html
{% extends 'base.html' %}

{% block containBody %}
<div class="modal fade show" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-modal="true" role="dialog" style="display: block;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'login' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>¿No estás registrado? <a href="{% url 'signup' %}">Crear cuenta</a></p>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript to hide the modal backdrop -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const myModal = new bootstrap.Modal(document.getElementById('loginModal'), {
            backdrop: 'static'
        });
        myModal.show();
    });
</script>

{% endblock containBody %}

proyecto_final/accounts/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    
    {% block containBody %}
    
    <div>
        <h1>Sesion cerrada</h1>
        <a href="{% url 'index' %}">Volver al Inicio</a>
    </div>

    {% endblock containBody %}

</body>
</html>

proyecto_final/accounts/templates/profile.html
{% extends 'base.html' %}

{% block containBody %}
<div>
    <H1>Bienvenido, {{ user.username }}!</H1>
</div>

<div class="d-flex justify-content-around align-items-center vh-100">
    <div class="card shadow-sm p-3 mb-5 bg-body rounded" style="width: 25rem;">
        <div class="card-bodyr d-flex flex-column justify-content-center align-items-center">
        {% if avatar_url %}
            <img src="{{ avatar_url }}" class="card-img-top" alt="avatar" style="max-width: 10rem;">
        {% endif %}
            <h5 class="card-title">{{ user.username }}</h5>
            <p class="card-text">{{user.email}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Nombre: {{user.first_name}}</li>
            <li class="list-group-item">Apellido: {{user.last_name}}</li>
            <li class="list-group-item">Edad: {{user.age}}</li>
            <li class="list-group-item">Domicilio: {{user.address}}</li>
        </ul>
        <div class="card-body d-flex flex-row align-self-center">
            <form class="" method="post" action="{% url 'logout' %}">{% csrf_token %}
                <button class="btn btn-outline-danger" type="submit">Cerrar Sesion</button>
            </form>
            <a href="{% url 'profile_edit' %}" class="btn btn-primary">Editar Perfil</a>
        </div>
    </div>
</div>

{% endblock containBody %}
    

proyecto_final/accounts/templates/profileEditForm.html
{% extends 'base.html' %}


{% block containBody %}
<div class="container mt-3">
    <h2 class="mb-4">Editar Perfil</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_email" class="form-label">Email</label>
            {{ form.email }}
        </div>
        
        <div class="mb-3">
            <label for="id_last_name" class="form-label">Apellido</label>
            {{ form.last_name }}
        </div>
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Nombre</label>
            {{ form.first_name }}
        </div>
        <div class="mb-3">
            <label for="id_age" class="form-label">Edad</label>
            {{ form.age }}
        </div>
        <div class="mb-3">
            <label for="id_address" class="form-label">Domicilio</label>
            {{ form.address }}
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Contraseña</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label">Repetir Contraseña</label>
            {{ form.password2 }}
        </div>
        <div class="form-check mb-3">
            <input type="checkbox" class="form-check-input" id="showPassword" onclick="togglePasswordVisibility()">
            <label class="form-check-label" for="showPassword">
                <i id="passwordIcon" class="fa fa-eye"></i> Mostrar Contraseña
            </label>
        </div>
        <div class="mb-3">
            <label for="id_url" class="form-label">Imagen</label>
            {{ avatar_form.imagen }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>

<script>
    function togglePasswordVisibility() {
        const passwordFields = document.querySelectorAll('.password-input');
        const icon = document.getElementById('passwordIcon');
        passwordFields.forEach(field => {
            if (field.type === 'password') {
                field.type = 'text';
                icon.classList.remove('fa-eye');
                icon.classList.add('fa-eye-slash');
            } else {
                field.type = 'password';
                icon.classList.remove('fa-eye-slash');
                icon.classList.add('fa-eye');
            }
        });
    }
</script>
{% endblock containBody %}
    

proyecto_final/accounts/templates/signup.html
{% extends 'base.html' %}

{% block containBody %}
<div class="modal fade show" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-modal="true" role="dialog" style="display: block;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Register</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <p>¿Ya tienes una cuenta? <a href="{% url 'login' %}">Iniciar sesion</a></p>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const myModal = new bootstrap.Modal(document.getElementById('loginModal'), {
            backdrop: 'static'
        });
        myModal.show();
    });
</script>

{% endblock containBody %}